### ISSUE TITLE
client.rates options.accepted doesn't work

### ISSUE THREAD

**Issue by ken-talkingsource** [OrahKokos/coinpayments#12] opened 2017-11-14 03:42 UTC
client.rates method
if options.accepted set to 1, still list all the currencies.
(but options.short works)

`
client.rates({ accepted: 1 }, (err, result) => {
	if(err) {
		console.log('-ERR!\n%s', err);
	} else {
		console.log('resault:');
		console.log(result);
	}
});
`

version 1.1.2

**Comment by OrahKokos** [comment] 2017-12-29 16:09
Will check it in the coming weeks. I was off for quite some time.

**Comment by OrahKokos** [comment] 2018-01-06 21:41
@ken-talkingsource Could not reproduce the issue. Please provide more feedback (err?). Also make sure that the API key that you are using has the correct permissions.

**Comment by OrahKokos** [comment] 2018-02-18 19:28
@ken-talkingsource 1.1.5 is out. Let me know if you have the same issue. Closing...

**Closed by OrahKokos** 2018-02-18 19:28 UTC
